<a href="https://colab.research.google.com/github/mlbl4/machine_learning_techniques/blob/main/Mar%C3%ADa_L%C3%B3pez_Badri_3_2_Supervised_Learning_NN_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.2 Supervised Learning: Neighborhood-based algorithms

- **Instructor**: Juan Ramón Rico
- **Student**: `María López Badri`
- `[TODO:]` Correct Colab submission to **be graded**:
  1. **Share this Colab** with `[juanramonua@gmail.com]`.
  2. **Send this notebook share URL** using `Practice / Form to send activity (URL Colab - Notebook)` in **Moodle-UA**.


## Abstract
---

The basic principles of neighborhood-based algorithms will be presented, specifically the one known as the $k$ nearest neighbor.

In [4]:
import numpy as np
import pandas as pd

## Neighborhood-based Techniques

- These techniques are based on distance functions that allow comparing input samples pairwise to obtain a measure of similarity or resemblance.
- One of the most used algorithms is called k-NN (k Nearest Neighbors), which relies on the target values of the nearest neighbors to:
   - estimate the density function and calculate the posterior probability, $P(ω_i |x) = k_i /k$, that a sample $x$ belongs to class $ω_i$ ($k_i$ is the number of neighbors of class i) in classification problems;
   - estimate the expected value in regression problems, usually by calculating the mean or median of the target values of the nearest neighbors.

In [5]:
## Test data

path = 'https://www.dlsi.ua.es/~juanra/UA/datasets'
path_tennis = f'{path}/tennis-en.csv'
path_covid19 = f'{path}/covid19-en.csv'

## Distance Function

In this case, we will use the most common one, the `Euclidean` or `L2` distance.

$$d_{L2}(\overrightarrow{x},\overrightarrow{y})=\sqrt{\sum_i(x_i-y_i)^2}$$

where $x$ and $y$ are vectors of numbers.

In [6]:
def d_L2(x,y):
  # Compute the Euclídea or L2 distance between two numeric vectors
  return np.sqrt(np.sum((x-y)**2))

# Test case
x = np.array([1,2])
y = np.array([2,3])

# Result 1.41
d_L2(x,y)

np.float64(1.4142135623730951)

## Example 1: Calculation of the Nearest Neighbor

We are going to implement a function whose parameters are a series of items and a set so that it calculates the nearest neighbor of each item to the given set.

In [7]:
def nearest_neighbors(sample, X_train):
  '''
    Find the nearest neighbor of a new sample to a training set (X_train)
  '''
  min_distance = float('inf')
  nearest_neighbor = None

  for x in X_train:
    distance = d_L2(sample, x)
    if distance < min_distance:
      min_distance = distance
      nearest_neighbor = x

  return  [sample, nearest_neighbor]

# Example test
X_test = np.array([ [1, 2], [1, 1], [8, 8] ])
X_train = np.array([ [1, 2], [3, 4], [5, 6], [7, 8] ])

# for each position in x_test array we see which one is the nearest form the X_train
for sample in X_test:
  print(nearest_neighbors(sample, X_train))

[array([1, 2]), array([1, 2])]
[array([1, 1]), array([1, 2])]
[array([8, 8]), array([7, 8])]

Results 🏆

Each line corresponds to the input item and its corresponding nearest neighbor.

```
[array([1, 2]), array([1, 2])]
[array([1, 1]), array([1, 2])]
[array([8, 8]), array([7, 8])]
```

## Example 2: Classification using Nearest Neighbors

Implement a Python function whose parameters are a set of samples with their respective classes (labels) and a sample to classify using the nearest neighbors algorithm. In this case, you can use the mode (the most repeated label) of the nearest neighbors as the label assigned to the new sample.

In [19]:
import statistics

def k_nearest_neighbors(X_train, y_train, sample, k, debug=False):
  '''
    Find the most common k labels among the nearest neighbors
  '''

  distances = []

  for x, y_label in zip(X_train,y_train):
      distance = d_L2(sample, x)
      distances.append((distance, y_label))

  # TODO: Sort all distances and their labels in ascending order
  distances.sort()
  if debug:
    print(f'sample: {sample} all distances: {distances}')

  # TODO: Get the most repeated label for the first k elements.
  labels = [label for _, label in distances[:k]]
  most_repeated_label = statistics.mode(labels) # Add code

  return most_repeated_label

# Use case
X_train = np.array([ [1, 2], [3, 4], [5, 6], [7, 8] ])
y_train  = ['A', 'B', 'A', 'B']
X_test  = np.array([[1,2], [4, 5]])
k = 3

for sample in X_test:
  print(k_nearest_neighbors(X_train, y_train, sample, k, debug=True))

sample: [1 2] all distances: [(np.float64(0.0), 'A'), (np.float64(2.8284271247461903), 'B'), (np.float64(5.656854249492381), 'A'), (np.float64(8.48528137423857), 'B')]
A
sample: [4 5] all distances: [(np.float64(1.4142135623730951), 'A'), (np.float64(1.4142135623730951), 'B'), (np.float64(4.242640687119285), 'A'), (np.float64(4.242640687119285), 'B')]
A

Results 🏆

```
output
x_test: [1 2] distances: [(0.0, 'A'), (2.8284271247461903, 'B'), (5.656854249492381, 'A'), (8.48528137423857, 'B')]
A
x_test: [4 5] distances: [(1.4142135623730951, 'A'), (1.4142135623730951, 'B'), (4.242640687119285, 'A'), (4.242640687119285, 'B')]
A
```

# Exercise 1: Tennis

## Basic implementation of the algorithms

Using the `Tennis` set and the necessary functions from the previous examples classify the following samples for a `k=3`:

In [9]:
test_examples = pd.DataFrame([
    ['sunny',  'high', 'high', 'no'],
    ['rain', 'high', 'high', 'yes'],
    ['overcast',  'high', 'high', 'no']
  ],
  columns=['weather', 'temperature', 'humidity', 'wind']
)
test_examples

    weather temperature humidity wind
0     sunny        high     high   no
1      rain        high     high  yes
2  overcast        high     high   no

In [10]:
# Load tennis data
data = pd.read_csv(path_tennis)
data
K=3


#TRAIN --> the ones we use to calculate de distance to the sample

X_train = data.iloc[:, :-1]
Y_train = data.iloc[:, -1]
X_test = test_examples

#We have categorical variables, so --> one-hot encoding

To use the `Euclidean` distance, we need to transform the class labels into a numerical format. For this purpose, we can use a conversion called `one-hot` encoding, which involves transforming each column containing a class into as many columns as its categories.

The `Pandas` package contains a function that performs this transformation, `pd.get_dummies()`, which we can use, or alternatively, we can implement a new function to do it.

---

⚠️ Warning: Remember that transformations are applied to the input variables to the model but not to the output (target) variable.

---

In [11]:
# TODO: Transform source data into a one-hot format

X_train_enc = pd.get_dummies(X_train, dtype=int)
#Y_train stays unchanged

We are going to use the same transformation as above but this time to the data of the new samples, variable `test_examples`.

In [14]:
# TODO: Transform test data (test_examples) into a one-hot format

X_test_enc = pd.get_dummies(X_test, dtype=int)

# the test data doesn't contain every category so we need
X_test_enc = X_test_enc.reindex(columns=X_train_enc.columns, fill_value=0)

Next we will search for the k nearest neighbors of the new samples in the training set and present their class prediction.

In [20]:
# TODO: Example of classification for tennis with k=3 of the test samples (test_data) with respect to the training samples (data)


for sample in X_test_enc.to_numpy():
  print(k_nearest_neighbors(X_train_enc.to_numpy(), Y_train, sample, k, debug=True))

sample: [0 0 1 1 0 0 1 0 1 0] all distances: [(np.float64(0.0), 'no'), (np.float64(1.4142135623730951), 'no'), (np.float64(1.4142135623730951), 'no'), (np.float64(1.4142135623730951), 'yes'), (np.float64(2.0), 'yes'), (np.float64(2.0), 'yes'), (np.float64(2.0), 'yes'), (np.float64(2.449489742783178), 'no'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.8284271247461903), 'no'), (np.float64(2.8284271247461903), 'yes')]
no
sample: [0 1 0 1 0 0 1 0 0 1] all distances: [(np.float64(1.4142135623730951), 'no'), (np.float64(1.4142135623730951), 'no'), (np.float64(2.0), 'no'), (np.float64(2.0), 'no'), (np.float64(2.0), 'yes'), (np.float64(2.0), 'yes'), (np.float64(2.0), 'yes'), (np.float64(2.449489742783178), 'no'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.8284271247461903), 'yes')]
no
sample: [1 0 0 1 0 0 1 0 1 0] all distances: [(np.float64(0.0), 'yes'), (np.float64(1.4142135623730951), 'no'), (np.float64(1.4142135623730951), 'yes'), (np.float64(2.0), 'no'), (np.float64(2.0), 'no'), (np.float64(2.0), 'yes'), (np.float64(2.0), 'yes'), (np.float64(2.449489742783178), 'no'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.449489742783178), 'yes'), (np.float64(2.8284271247461903), 'no'), (np.float64(2.8284271247461903), 'yes')]
yes

## Implementation with scikit-learn

The `scikit-learn` package contains various functions based on neighborhood algorithms. For classification, there is the `sklearn.neighbors.KNeighborsClassifier()` function that we can use for training first and then predicting new values.

In [24]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3) # Euclidean distance is used by deafault

X_train = data.iloc[:, :-1]
Y_train = data.iloc[:, -1]

X_train_enc = pd.get_dummies(X_train, dtype = int)
X_test_enc = pd.get_dummies(test_examples, dtype=int).reindex(columns=X_train_enc.columns, fill_value=0)

model.fit(X_train_enc, Y_train)
print(model.predict(X_test_enc))

# Classify 'test_data' based on 'data' using sklearn functions

['no' 'no' 'yes']

Results 🏆

```
array(['no', 'no', 'yes'], dtype=object)
```

# Exercise 2: COVID-19

## Basic implementation of the algorithms

Using the `COVID-19` dataset and the necessary functions from the previous examples, classify the following samples for a `k=3`:

In [26]:
test_examples = pd.DataFrame([
    ['Yes',  'No', 'No'],
    ['No',  'Yes', 'No'],
    ['No',  'Yes', 'Yes'],
  ],
  columns=['Fever', 'Cough', 'Respiratory Problems']
)
test_examples

  Fever Cough Respiratory Problems
0   Yes    No                   No
1    No   Yes                   No
2    No   Yes                  Yes

In [25]:
# Load COVID-19 data
data = pd.read_csv(path_covid19, index_col=0)
data

X_train = data.iloc[:, :-1]
Y_train = data.iloc[:, -1]

Similary to the previous exercise, to use the `Euclidean` distance, we need to transform the class labels into a numerical format. For this purpose, we can use a conversion called `one-hot` encoding, which involves transforming each column containing a class into as many columns as its categories.

The `Pandas` package contains a function that performs this transformation, `pd.get_dummies()`, which we can use, or alternatively, we can implement a new function to do it.

---

⚠️ Warning: Remember that transformations are applied to the input variables to the model but not to the output (target) variable.

---

In [27]:
# TODO: Transformation of training data to a one-hot format

X_train_enc = pd.get_dummies(X_train, dtype=int)

Let's use the same transformation as before, but this time on the data of the new samples, variable `test_examples`.

In [28]:
# TODO: Transforma test data (test_data) to a one-hot format

X_test_enc = pd.get_dummies(test_examples, dtype=int)

Next, we will find the k nearest neighbors to the new samples from the training set and present the prediction of their class.

In [31]:
# TODO: Example of classification for COVID-19 with k=3 of the test samples (test_data) with respect to the training samples (data)

for sample in X_test_enc.to_numpy(): #looping over a DataFrame gives you its column names, but looping over a NumPy array gives you its rows
  print(k_nearest_neighbors(X_train_enc.to_numpy(), Y_train, sample, k, debug=True))

sample: [0 1 1 0 1 0] all distances: [(np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(2.0), 'No'), (np.float64(2.0), 'No'), (np.float64(2.0), 'Yes'), (np.float64(2.0), 'Yes'), (np.float64(2.449489742783178), 'No'), (np.float64(2.449489742783178), 'Yes'), (np.float64(2.449489742783178), 'Yes')]
No
sample: [1 0 0 1 1 0] all distances: [(np.float64(0.0), 'No'), (np.float64(0.0), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(2.0), 'Yes'), (np.float64(2.0), 'Yes'), (np.float64(2.449489742783178), 'Yes'), (np.float64(2.449489742783178), 'Yes'), (np.float64(2.449489742783178), 'Yes')]
No
sample: [1 0 0 1 0 1] all distances: [(np.float64(0.0), 'No'), (np.float64(0.0), 'Yes'), (np.float64(0.0), 'Yes'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'No'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(1.4142135623730951), 'Yes'), (np.float64(2.0), 'No'), (np.float64(2.0), 'No'), (np.float64(2.0), 'No'), (np.float64(2.0), 'Yes'), (np.float64(2.0), 'Yes'), (np.float64(2.0), 'Yes'), (np.float64(2.0), 'Yes')]
Yes

## Implementation with scikit-learn

The `scikit-learn` package contains various functions based on neighborhood algorithms. For classification, there is the `sklearn.neighbors.KNeighborsClassifier()` function that we can use for training first and then predicting new values.

In [30]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3) # Euclidean distance is used as default

model.fit(X_train_enc, Y_train)
print(model.predict(X_test_enc))
# Classify 'test_data' based on 'data' using sklearn functions

['No' 'No' 'Yes']

Results 🏆

```
array(['No', 'No', 'Yes'], dtype=object)
```

## AI-Assisted Code Optimization Exercise

Use a generative AI tool to optimize the implementation of the **k-NN algorithm** (base) provided in the notebook.

* **Optimize the code:** Use a generative AI tool to improve the efficiency of the original implementation.
* **Explain the changes:** Briefly describe the main changes introduced by the AI-generated version and explain how they improve the computational efficiency of the original code.
* **Validate the result:** Test the optimized implementation using one of the examples from the notebook and verify that it produces results equivalent to those of the original implementation.